## Preprocessing

In [ ]:
# Import our dependencies
%pip install tensorflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.12.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.56.2)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.13)
Requirement already satisfied: keras<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: numpy<1.24,>=1.22 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.22.4)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.3)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.7.1)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.32.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.41.0)
Requirement already satisfied: ml-dtypes>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow) (0.2.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (3.4.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.27.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.3.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow) (3.2.2)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df= application_df.drop(columns = ['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
from numpy.lib.shape_base import apply_along_axis
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_type = application_df['APPLICATION_TYPE'].value_counts()
app_type

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(app_type.iloc[8:].index)
cutoff_vlaue = 528
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_types_binning = application_df['CLASSIFICATION'].value_counts()
class_types_binning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts = class_types_binning[class_types_binning >1]
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
class_types_binning.iloc[5:].index

Index(['C7000', 'C1700', 'C4000', 'C5000', 'C1270', 'C2700', 'C2800', 'C7100',
       'C1300', 'C1280', 'C1230', 'C1400', 'C7200', 'C2300', 'C1240', 'C8000',
       'C7120', 'C1500', 'C1800', 'C6000', 'C1250', 'C8200', 'C1238', 'C1278',
       'C1235', 'C1237', 'C7210', 'C2400', 'C1720', 'C4100', 'C1257', 'C1600',
       'C1260', 'C2710', 'C0', 'C3200', 'C1234', 'C1246', 'C1267', 'C1256',
       'C2190', 'C4200', 'C2600', 'C5200', 'C1370', 'C1248', 'C6100', 'C1820',
       'C1900', 'C1236', 'C3700', 'C2570', 'C1580', 'C1245', 'C2500', 'C1570',
       'C1283', 'C2380', 'C1732', 'C1728', 'C2170', 'C4120', 'C8210', 'C2561',
       'C4500', 'C2150'],
      dtype='object')

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_types_binning.iloc[5:].index)
cutoff_value_class = 1883

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df['IS_SUCCESSFUL'].values

y

array([1, 1, 0, ..., 0, 1, 0])

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0859000e+05, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       ...,
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.0000000e+03, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.6500179e+07, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

In [ ]:
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 8)                 400

 dense_7 (Dense)             (None, 5)                 45

 dense_8 (Dense)             (None, 1)                 6

=================================================================
Total params: 451
Trainable params: 451
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6004 - accuracy: 0.6960
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5638 - accuracy: 0.7244
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5581 - accuracy: 0.7266
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5559 - accuracy: 0.7290
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7290
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7291
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7303
Epoch 8/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5517 - accuracy: 0.7303
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5508 - accuracy: 0.7297
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5498 - accuracy: 0.7297
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7309
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7313
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7299
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5476 - accuracy: 0.7314
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7313
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7307
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7318
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7318
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7315
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7326
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7318
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7327
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7333
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7336
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7341
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7336
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7349
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7336
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7332
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7345
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7339
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7344
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7348
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7346
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7346
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7349
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7346
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7346
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7350
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7352
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7357
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7347
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7348
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7354
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7349
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7346
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7358
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7348
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7350
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7351
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7356
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7351
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7358
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7358
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7350
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7347
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7361
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7347
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7358
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7354
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7352
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7353
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7358
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7359
Epoch 69/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5411 - accuracy: 0.7357
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7348
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7366
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7362
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7357
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7350
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7357
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7353
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7359
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7353
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7355
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7352
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7359
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7355
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7355
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7363
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5407 - accuracy: 0.7362
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7360
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7361
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7360
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7357
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7352
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7361
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7366
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7359
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7370

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5529 - accuracy: 0.7247 - 537ms/epoch - 2ms/step
Loss: 0.5529449582099915, Accuracy: 0.7246647477149963

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('AlphabetSoupCharity.h5', save_format='h5')